### ISSUE TITLE
can't open reder96!!

### ISSUE THREAD

**Issue by axelpersevalle** [enigma9o7/smlinux#31]
hello,
all is already except that the compilation is succesful any idea?
thanks
bye, Axel

**Comment by enigma9o7** [comment]
Sorry I'm not sure what you're suggesting the problem is.  If script is compiling successfully then it's doing it's job.  

What does can't open mean?   If you think its a script problem, provide screenshot or log of error, and what OS you're using.

If you mean r96 models wont direct apply to render96ex, yes that is known issue, I am not sure how to do it with current version actually, so disabled it in script instead to avoid failed builds.  You can still load those models from dynamic options tho, or direct apply them to another repo.

**Comment by axelpersevalle** [comment]
hey,
I took a video and a picture of my terminal you will see that the compile is successful but I can't open it..
![Capture d’écran du 2021-03-24 12-53-33](https://user-images.githubusercontent.com/78932119/112306483-221e5000-8ca0-11eb-823f-6879e3013cd1.png)


https://user-images.githubusercontent.com/78932119/112306172-d075c580-8c9f-11eb-87ec-3da34774e52b.mp4

**Comment by enigma9o7** [comment]
I'll check into this later, I havent watched the videos, but seen the screenshot at the end showing its unable to find sound, I have an immediate idea... Did you change the LEGACY_RES flag?  

I think this may need to be disabled for render96ex's alpha branch (which is what the render96ex preset uses)  If enabled it uses the old method for resource packs which I think doesnt work with their external languages...  I may have a bad default there possibly and I will reply again after I watch your videoes and check the script, but just wanted to suggest this now since I saw the message but can't look into it right away...

**Comment by enigma9o7** [comment]
I have made several changes that should resolve any issues building render96ex current versions.  I do not believe it should be possible now for smlinux to make a broken clean build, no matter of what options selected etc.   

so my suggestion is smlinux build, select render96ex and desired options, and if all works, great.

If that doesnt work, its possible the render96ex repository got corrupted.  I had this happen myself and couldn't get it to reset properly, so ended up deleting myself and letting smlinux download again.

If you still have any issues after trying current version, please reopen this issue and describe and I'll look into right away.
