### ISSUE TITLE
[Request] Support for custom patches

### ISSUE THREAD

**Issue by Tau5** [enigma9o7/smlinux#9]
It would be useful to be able to add custom patches and select whick patches to apply trogh dialog. This could be posible by having the custom patches in a directory in home or a directory next to the executable

**Comment by enigma9o7** [comment]
A few thoughts on this.  

Of course if something were to be implemented I'd use the enhancements directory, just like the existing patches and like I suggest in the FAQ under applying patches.

I looked at dialog a while ago for file selection, its UI is not very intuitive imo, I didnt like it.   

Main point of this script, after first install, is to handle updates/rebuilds so you don't have to manually deal with external resources and backups or have to remember your make command line.  So it already makes applying patches easy, that was one of the main uses for this script already, the 3rd being updating sm64 to latest from github repo.

Patches are so easy to install, and a one time thing usually, it hardly needs further automation.  Plus patches are likely to cause problems with updates, etc, so would require a lot of work to handle them correctly when scripted.  Plus if people try to apply inapplicable patches or patches that cause build failure, they're likely to not pay as much attention if script handling it instead of if they just did it themself and might miss the failure messages...

That being said, if I or someone ever does write a GUI for this, I might consider putting something in there for applying patches.  But since applying a patch is already a very simple single command and script already made to allow user adding patches, I see no reason to change existing version of script.

That being said, doesn't mean you can't add something to your own copy if you think it'd make it easier for you to add patches, and feel free to submit as PR if you want, if it doesn't affect normal functionality I wouldn't be opposed to adding it.
